"""Polity-002: friction measurement on conflict the project did not author.

The arena (round dynamics, network, protocol) is the project's. The conflict
content in docs/polity-002/minds.json was generated by four separate subagent
minds under opposed mandates — the project stood up the arena but did not
author the conflict, per the prime directive.
"""

import json
from pathlib import Path

from law_and_order import RuleSet
from law_and_order.protocol import Phase
from law_and_order.sim.engine import CRITICAL_FRICTION, WINDOW, run
from law_and_order.sim.population import Persona

ROUNDS = 60
SEED = 7
ROOT = Path(__file__).resolve().parent.parent
COUNTERPARTS = {
    "buyer": ("seller", "creditor"),
    "seller": ("buyer", "debtor"),
    "creditor": ("debtor", "buyer"),
    "debtor": ("creditor", "seller"),
}


def load_population() -> tuple[Persona, ...]:
    minds = json.loads((ROOT / "docs" / "polity-002" / "minds.json").read_text(encoding="utf-8"))
    return tuple(
        Persona(
            name=name,
            claims=tuple(mind["claims"]),
            noise=tuple(mind["noise"]),
            counterparts=COUNTERPARTS[name],
        )
        for name, mind in minds.items()
    )


def main() -> None:
    ruleset = RuleSet.from_json((ROOT / "rulesets" / "v2.json").read_text(encoding="utf-8"))
    population = load_population()

    baseline, _, _ = run(population, ROUNDS, SEED)
    installed, published, resolved = run(
        population, ROUNDS, SEED, installed=True, ruleset=ruleset
    )

    print("round  baseline  installed")
    for index in range(0, ROUNDS, 5):
        print(f"{index:>5}  {baseline[index].friction:>8.3f}  {installed[index].friction:>9.3f}")

    baseline_tail = sum(record.friction for record in baseline[-WINDOW:]) / WINDOW
    installed_tail = sum(record.friction for record in installed[-WINDOW:]) / WINDOW
    baseline_phase = Phase.ORDERED if baseline_tail < CRITICAL_FRICTION else Phase.DISORDERED
    installed_phase = Phase.ORDERED if installed_tail < CRITICAL_FRICTION else Phase.DISORDERED

    print()
    print(f"baseline tail friction:  {baseline_tail:.3f}  ({baseline_phase.value})")
    print(f"installed tail friction: {installed_tail:.3f}  ({installed_phase.value})")
    print(f"friction delta:          {baseline_tail - installed_tail:.3f}")
    print(f"rulings published:       {len(published)}")
    print(f"disputes resolved:       {resolved}")


if __name__ == "__main__":
    main()
